apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: codeserver
    namespace: dev
spec:
    interval: 15m
    chart:
        spec:
            chart: code-server
            version: 13.15.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: traefik
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                hosts:
                    - host: ide.${DOMAIN_0}
        persistence:
            datastoragepath:
                enabled: true
                mountPath: /root
                path: '${USER_HOME_DIR}'
                server: '${NFS_SERVER}'
                type: nfs
            config:
                enabled: true
                mountPath: /config
                path: '${USER_HOME_DIR}/vscode_config'
                server: '${NFS_SERVER}'
                type: nfs
