apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: route-fileserver
    namespace: flux-system
spec:
    interval: 10m
    path: clusters/main/kubernetes/routers/route-fileserver/app
    prune: true
    sourceRef:
        kind: GitRepository
        name: cluster
