apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cloudflared
    namespace: routers
spec:
    interval: 15m
    chart:
        spec:
            chart: cloudflared
            version: 13.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        securityContext:
            container:
                UMASK: '0022'
                runAsGroup: 0
                runAsUser: 0
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                TUNNEL_TOKEN: ${CLOUDLARED_TUNNEL_TOKEN}
