apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tLjJiI5kArLRaZHbbvqbzIsRUWfIHOpd5TOoMzNdUAUN1/lJbRocrEi+6OftNe/OliUTXnn5+WT7aEM5UgBL0r5xvgdykFUVZH8voXfcs/j+e4IU1EUu7SvgttanjZFcVuntjoZCkKrHc3W/+cT9p+xVuJuLOmzlaM6KFYHE6vVydyQBmek4OmvU6L7PQB3hKe7ubYvgx9xUDiwKDIYbEJmmX4FV8bwArOkVjMwTwLlpbvq24RgWVTQRAN5am/H/MSEM7M6EQV5bCZyBgJ3GrX8FxQ8AdmozG/VDTRM9sdn3v9xeyWGb5usyn/iZQPcqtMoeUWSFSJy5w0pQqaZjz8rs1dnNXUIVgXqBnvWWhnwd7eq6OC2sIt9uC6sFE8mw,iv:N8Kbhwi2JagBXkGqM2Kgxgv/eoTl0UuU0tqq27Y/54Q=,tag:dmQKSBFCbvdnDjlSBCQS2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:UJLkGkMdNdZ9O7IgNgdmDDk0ylC2IQvgTiH67CVg7S3TY58qvDQul0FgU9tV0wRvtk8YdBBGrDqPjcLGEhGBRd0gPmH2Mqo1hGzFDIi43Y2R5+Dc5B4b8mpI/QyhRg+1vofeAiNSqohJlf4Ynn89d1ozyh9U6dN2cN4xb9tCNFH8ESrDj8LhMT52ylG4Iz/TuiSKcmV6kWNTBKFdinecGoqoiA2nmtizZ5giHVm6D+/SzUq3X93dOEXmJfoOQb1ar40bWGwLJf8/OkHxNg==,iv:aArSSHDZ4DPb2sRndxsWrIh/PSVmXMHRwSMCENBX9nc=,tag:ZFgebzWMdkZvPOAtZrOwiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zlbk7ScWOfhwq/bYgaqsINexHXYiklGjpM8AZe0GfG9LRpp0VlMEySv+td9UblLG1qRmcGDPqInEDBGfPHDrZe3iuzjUQXVTpMJXTCP0zQMysaqB5RH03NxRg7D6g4VQ5JMZi88+a4AQl8ejPZjXq8S6v7uXGaN6IWtY5Qp85UAuyjQNYw43F2tFqhloDFSqCisqS07MnhgZswgO4LPislo//Ztkx6ZfZyoV,iv:8/9rZu5Qkw3Qe7ZrZrEv9wkn9WO0YcRlivur1iqc78g=,tag:+KyWutT6uBgsyAJ3O0f1NQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kngpncm3nx3t886x8797lrzu76m8esfeseplu0pzepmg7f3t92q0rue8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TDdLdTJmNDFIb240Nko2
            SXZIS2hzUk05UFRtVEFjQnhmMndIVTZLV0NnCnZVbWpFS1VBV3A5TVE0eHZLZlpV
            MVRQRVZ3S1ZSVWpIamxNQnJ3YzR6Vm8KLS0tIHBmUGpNUFNPUW9LN0RSeHpDRXBC
            UEt0ZjZ4eWp1NUJOSFB3Y0xjcFZuTEUK8ItPVesjqE7h1yP8G9AR0dFqTC41rNgq
            4smaPFzS5W5hQEtJwI1DrbsTwH0wLuQeS2jULRbxv4LWeC+69vEDvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T09:13:31Z"
    mac: ENC[AES256_GCM,data:6relIAzUPWyrqWwJbEFBvdSKF2jsUa+lf5g2XO+DH567AuVRZD1vSGi9yuTsFO4qprew/rzsbKGz5fGADDpkR8Qocwj7atlyNNl8RGThniBa6n1RcpByX6hWfS87bbl59j+uRYuC7hOOevenhbTfJ0nhCysvfrr1n2I7aCGXOKo=,iv:dke7OhewsRc1nnmooUKmPRtYLpyKY2C4PIG5KGzWrvQ=,tag:zPDUjGp7934GD05U4JyolQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
