apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UAI3ODXbInzkanjvgVdTLXWLy18dJ6uNQNx4v8OtzCew9T7VshzSek7A8GljJSKK39/S0l3sdYtyjQe30oZ5NuwrKQTuZ/AdOKXHpGfRr9TO+/hJdON8vFj/38iRYaM638Q6DRk7/kjSc9n4B76uUv5huuzX73GOR7+hlRXHNQQtIwB/elsdeIbL2WWYBeJUQisnfLPmKFUWuoTgH3fOvGUt0a42NK8pN1C+VW57c9M/uT80sYPiehWTzNbC2NeDo8kq43N40N5fHwf/+QMjvbdns3pYQjiWxYK4V7Zg5sh0D06Tt3HgA3nLtakC1Gw9wDIwHaxQ4ye9si4HcskbGBn3zQCQ5sGmUqCkB5gO8NuYrslfr+qR5u4R9VS65rz0,iv:ddO8q3Ug5nJ7J6C49YVd1T70Klbvofja9JRtV86k+7o=,tag:hC0Iqq8HWZt/6YSTZ2jqYQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:+WPKDX4iyRtGFNzZ0sjOLbMBgWH+LfrP5CP6mMZFHeMu1KbBdlOCp59sznGwy9soCQfBdfF2e035qNaeXQZ4UVXIXmU7lVlP3DeF1BSq/mRp7zto+SlXiwS9E7cFk3neInjWia6Kl0U0k5jjiRdKc4EByILtzG9orLQ7bQ//qQgG0HHv1E5zA4zHpNHNXDtdyjoAsrEhetgFQ16bBVwtW9pKQ4sy+5aDAsSLAiiwUXk/ust0dqrpzPSSJ5uqZWt9gy2R1HQwlYDrU1tNRw==,iv:QgB2OzjuUfIhJu83IZHB3HSMFP0zo1wIGSeNZHknyfc=,tag:d5d5slv5Omb0yK+KmVtU9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:EBtWHT91xoCujtQ9nRfFgV7K0tt6x8RnJOFXnhgcpZmKFxsdOaeE7UirSDpD3u1x1sdtGM1zkrtOhIxbBfKhacstILHVWATtF8Dyn8sAMZVk2KTojov9OXCpyjyO5O/kxFuOAH0UzqjfIrSJWxEOpCoQUp5+ADmnVr3bndk2gZ/vzZUfTjMIadbWQSLODv0q78NioR7i+sTrl7wPqgZEvA6sjwIRFgtBCDtk,iv:J34fVWXrWN7To2VDF5qPsbDIaLCtrNvUmQBv1nYBGho=,tag:DJK7FMWhGsJpH5LYsHBF0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17kngpncm3nx3t886x8797lrzu76m8esfeseplu0pzepmg7f3t92q0rue8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWVg1RUFvekdnWURWZ1RK
            bXZPaDN0SEI2Mi9LM3FEeUJKNEE1RTY3NnhzCkVEUi9Ud0VKek9lYTAvTHBpRm5G
            anJPc2RQYXlYTGpOU0NnY3RKTk9zWGsKLS0tIHVOY2RmT0labUpXN2s4aXNRRU9n
            S1JWa0l0WFNDaWpFNXZxY0FJRjhkdEUKSfBNANBHUApmwrfbj1aYIu+Ta2i22tK0
            RFg9eCMTEbEnnkYnLG6+1cS6G7PujGfJKeJIglRt240U/BUtIW2ZvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T11:57:18Z"
    mac: ENC[AES256_GCM,data:mjYZwmAIMMTaRa4DCjAs3gnPE72tBD0ASFS58E9Z+9ryjWK8TKTnvlLwl4vYiQ0C8ycBElRIYTC2IdrhlLSOtuWhP6n53/8OvjhAADTM2LW6EzoowdQ30JcEhrzw+EE0JAwFsd77U1eb2sTvPRP3DZNi1OtElQnGygOPTHiq2JY=,iv:loBEulOyrGBpDPkYpJ+2xxna76d1A5wzcpU7Qqj6n0w=,tag:tqaIejScYbTwb8zi2Tv7og==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
