apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: dashboards
spec:
    interval: 15m
    chart:
        spec:
            chart: homepage
            version: 10.1.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: auth
                              namespace: traefik
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                hosts:
                    - host: homepage.${DOMAIN_0}
        persistence:
            config:
                enabled: true
                mountPath: /app/config
                path: '${NFS_CONTAINERS_DATA}/homepage'
                server: '${NFS_SERVER}'
                type: nfs
