apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authelia
    namespace: auth
spec:
    interval: 15m
    chart:
        spec:
            chart: authelia
            version: 27.1.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: auth.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                    homepage:
                       enabled: true
                       group: System
                    traefik:
                        enabled: true
                required: true
        cnpg:
            main:
                cluster:
                    instances: 1
                    singleNode: true
                enabled: true
                hibernate: false
                database: authelia
                user: authelia
                password: ${CNPG_PASSWORD}
        authelia:
            theme: dark
            authentication_backend:
                password_reset:
                    disable: false
                ldap:
                    implementation: custom
                    address: ldap://lldap-ldap.auth.svc.cluster.local:3890
                    base_dn: DC=ldap,DC=${DOMAIN_0_BASE},DC=${DOMAIN_0_EXTENSION}
                    attributes:
                        username: uid
                        group_name: cn
                        mail: mail
                        display_name: displayName
                    additional_users_dn: ou=people
                    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
                    additional_groups_dn: ou=groups
                    groups_filter: (member={dn})
                    user: uid=admin,ou=people,DC=ldap,DC=${DOMAIN_0_BASE},DC=${DOMAIN_0_EXTENSION}
                    password: ${LDAP_PASSWORD}
            access_control:
                default_policy: one_factor
                rules:
                    - domain:
                        - mflix.${DOMAIN_0}
                      domain_regex: []
                      networks:
                          - 172.16.0.0/16
                          - 172.17.0.0/16
                          - '${BASE_IP}.0/24'
                      policy: bypass
                      resources:
                          - ^/memUsage
                      subject: []
                    - domain:
                        - mflix.${DOMAIN_0}
                      domain_regex: []
                      networks: []
                      policy: bypass
                      resources:
                          - ^/xtream/live/
                          - ^/assets/
                      subject: []
            session:
                cookies:
                    - domain: ${DOMAIN_0}
                      default_redirection_url: https://${DOMAIN_0}
                      authelia_url: https://auth.${DOMAIN_0}
            notifier:
                smtp:
                    address: submissions://${SMTP_HOST}:${SMTP_PORT}
                    username: ${DOMAIN_0_EMAIL}
                    # TODO: https://www.authelia.com/configuration/methods/secrets/
                    password: ${SMTP_PASSWORD}
                    sender: ${DOMAIN_0_EMAIL}
                    startup_check_address: ${DOMAIN_0_EMAIL}
            # identity_providers:
            #     oidc:
            #         access_token: 1h
            #         authorize_code: 1m
            #         clients:
            #             - audience: []
            #               authorization_policy: one_factor
            #               consent_mode: auto
            #               client_name: Cloudflare ZeroTrust
            #               grant_types:
            #                   - refresh_token
            #                 #   - authorization_code
            #               client_id: cloudflare
            #               public: false
            #               redirect_uris:
            #                   - https://${DOMAIN_0_BASE}.cloudflareaccess.com/cdn-cgi/access/callback
            #               require_pkce: false
            #               response_modes:
            #                   - form_post
            #                   - query
            #                   - fragment
            #               response_types:
            #                   - code
            #               scopes:
            #                   - openid
            #                   - profile
            #                   - email
            #               client_secret: $pbkdf2-sha512$310000$S4HLrTiEzXIw3zqJiTdOyw$Fmfm2il4uEapk1nu.Zvsh4DzE6K9YMRuYWDuVDTGW6jhAwCEmfZkG/m1AwD3BGfgd8ALuqenK0hAZlkuHd8Abw
            #               token_endpoint_auth_method: client_secret_basic
            #               userinfo_signed_response_alg: none
            #         enable_client_debug_messages: false
            #         id_token: 1h
            #         minimum_parameter_entropy: 8
            #         refresh_token: 90m
            # TODO:  time="2025-04-09T08:13:04Z" level=error msg="Configuration: identity_providers: oidc: option `jwks` is required" => https://www.authelia.com/configuration/identity-providers/openid-connect/provider/#jwks
            # TO VERIFY: time="2025-04-09T08:13:04Z" level=warning msg="Configuration: identity_providers: oidc: clients: client 'cloudflare': option 'client_secret' is plaintext but for clients not using any endpoint authentication method 'client_secret_jwt' it should be a hashed value as plaintext values are deprecated with the exception of 'client_secret_jwt' and will be removed in the near future"
