apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: auth
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 7.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    cnpg:
      main:
        cluster:
          instances: 1
          singleNode: true
        database: lldap
        enabled: true
        hibernate: false
        password: ${CNPG_PASSWORD}
        user: lldap
        mode: recovery
        backups:
          credentials: CFR2
          enabled: true
          revision: "1"
          scheduledBackups:
            - name: daily-backup
              schedule: '0 0 2 * * *'
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          # revision: "1"
          method: object_store
          credentials: CFR2
    credentials:
      CFR2:
        accessKey: '${S3_ACCESS_KEY}'
        bucket: '${S3_BUCKET}'
        name: CFR2
        secretKey: '${S3_SECRET_KEY}'
        type: s3
        url: '${S3_URL}'
        encrKey: '${S3_ENCR_KEY}'
    persistence:
      data:
        volsync:
          - name: data
            credentials: CFR2
            dest:
              enabled: true
            src:
              enabled: true
            type: restic
    ingress:
      main:
        enabled: true
        hosts:
          - host: ldap.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: '${DOMAIN_0_BASE}-prod'
            enabled: true
          homepage:
            enabled: true
            group: System
          traefik:
            enabled: true
            entrypoints:
              - websecure
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_LDAP_BASE_DN: dc=ldap,dc=${DOMAIN_0_BASE},dc=${DOMAIN_0_EXTENSION}
                LLDAP_LDAP_USER_EMAIL: ${DOMAIN_0_EMAIL}
                LLDAP_LDAP_USER_PASS: ${LDAP_PASSWORD}
                LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <alerts@${DOMAIN_0}>
                LLDAP_SMTP_OPTIONS__PASSWORD: ${SMTP_PASSWORD}
                LLDAP_SMTP_OPTIONS__PORT: ${SMTP_PORT}
                LLDAP_SMTP_OPTIONS__REPLY_TO: Do not reply <noreply@${DOMAIN_0}>
                LLDAP_SMTP_OPTIONS__SERVER: ${SMTP_HOST}
                LLDAP_SMTP_OPTIONS__USER: ${DOMAIN_0_EMAIL}
                smtp: true
