apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: it-tools
    namespace: misc
spec:
    interval: 15m
    chart:
        spec:
            chart: it-tools
            version: 7.6.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                    certManager:
                        certificateIssuer: "${DOMAIN_0_BASE}-prod"
                        enabled: true
                hosts:
                    - host: tools.${DOMAIN_0}
