apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: gitea-runner
    namespace: dev
spec:
    interval: 15m
    chart:
        spec:
            chart: gitea-runner
            version: 0.0.1
            sourceRef:
                kind: HelmRepository
                name: mehdif
                namespace: flux-system
    releaseName: gitea-runner
    replicas: 1
    values:
