apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: shorturl
    namespace: shorturl
spec:
    interval: 15m
    chart:
        spec:
            chart: shorturl
            version: 12.5.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: shorturl
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: url.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
