apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: zigbee2mqtt
    namespace: flux-system
spec:
    interval: 10m
    path: clusters/main/kubernetes/smarthome/zigbee2mqtt/app
    prune: true
    sourceRef:
        kind: GitRepository
        name: cluster
