apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: route-fileserver
  namespace: routers
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: fileserver.${DOMAIN_0}
        integrations:
          certManager:
            certificateIssuer: '${DOMAIN_0_BASE}-prod'
            enabled: true
          traefik:
            enabled: true
            entrypoints:
              - websecure
            # middlewares:
            #     - name: auth
            #       namespace: traefik
    service:
      main:
        enabled: true
        type: ExternalIP
        externalIP: '${NFS_SERVER}'
        ports:
          main:
            enabled: true
            port: 12321
            protocol: https

