apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: dev
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 17.12.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        service:
            main:
                type: LoadBalancer
                loadBalancerIP: '${PGADMIN_IP}'
                ports:
                    main:
                        port: 80
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PGADMIN_DEFAULT_EMAIL: '${DOMAIN_0_EMAIL}'
                                PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
