apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: plex
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: plex
            version: 19.6.11
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        plex:
            serverIP: "${PLEX_IP}"
        service:
            main:
                type: LoadBalancer
                loadBalancerIP: "${PLEX_IP}"
        persistence:
            datastoragepath:
                enabled: true
                mountPath: /data
                path: "${MEDIA_PATH}"
                server: "${NFS_SERVER}"
                type: nfs
