apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: smarthome
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: home-assistant
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: home.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            certificateIssuer: '${DOMAIN_0_BASE}-prod'
            enabled: true
          homepage:
            enabled: true
            group: Smart Home
          traefik:
            allowCors: false
            enabled: true
            entrypoints:
              - websecure
    credentials:
      CFR2:
        accessKey: '${S3_ACCESS_KEY}'
        bucket: '${S3_BUCKET}'
        name: CFR2
        secretKey: '${S3_SECRET_KEY}'
        type: s3
        url: '${S3_URL}'
        encrKey: '${S3_ENCR_KEY}'
    cnpg:
      main:
        enabled: true
        user: home-assistant
        password: ${CNPG_PASSWORD}
        database: home-assistant
        mode: recovery
        backups:
          credentials: CFR2
          enabled: true
          revision: "1"
          scheduledBackups:
            - name: daily-backup
              schedule: '0 0 2 * * *'
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: CFR2
    persistence:
      config:
        enabled: true
        mountPath: /config
        path: ${NFS_CONTAINERS_DATA}/homeassistant/config
        readOnly: false
        server: '${NFS_SERVER}'
        targetSelectAll: true
        type: nfs
    securityContext:
      container:
        capabilities:
          add: []
